# Artificial Neural Network

### Importing the libraries

In [41]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [42]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [43]:
dataset = pd.read_csv('Data.csv', sep=';')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [44]:
print(X)

[[ 1  0  0 ...  0  0  0]
 [ 2  0  0 ...  0  0  0]
 [ 3  0  0 ...  0  0  0]
 ...
 [25  1  0 ...  0  0  0]
 [26  0  4 ...  0  1  0]
 [27  0  0 ...  0  0  0]]


In [45]:
print(y)

[ 4  6  8  9 11 10  8  8  7  6  5  4  4  4  5  5  6  5  6  8  9  9  9 11
 11 11  7  4  6  8  9 10  9  7  7  8  8  8  7  8  7  8  8  8  8  9 11 12
 13 13 15 16 15 11  3  3  5  5  7  7  6  6  6  7  8  8  8  6  6  8  9 10
 12 13 15 17 19 20 22 23 19  4  5  5  5  8  7  7  6  7  7  7  7 10 10 11
 12 12 10  9 11 12 13 15 18 19 21 22  3  5  5  6  8  9 10 10 10 12 11 10
 11  9 10 10  8  9 11 13 14 17 17 18 17 17 12]


### Splitting the dataset into the Training set and Test set

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [47]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [48]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))

### Adding the second hidden layer

In [49]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))

### Adding the output layer

In [50]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [51]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [52]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
4/4 [==============================] - 0s 2ms/step - loss: 109.4733
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 90.1483
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 73.8001
Epoch 4/100
4/4 [==============================] - 0s 2ms/step - loss: 59.2041
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 47.7588
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 37.6464
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 29.8343
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 23.6752
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 18.8137
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 15.2499
Epoch 11/100
4/4 [==============================] - 0s 2ms/step - loss: 13.1785
Epoch 12/100
4/4 [==============================] - 0s 2ms/step - loss: 11.7155
Epoch 13/100
4/4 [==============================

### Predicting the results of the Test set

In [53]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=0)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 8. 11.]
 [ 7.  7.]
 [12.  9.]
 [11. 11.]
 [ 4.  5.]
 [ 7.  7.]
 [14. 15.]
 [13. 18.]
 [12.  9.]
 [ 7.  9.]
 [12. 13.]
 [11. 12.]
 [14. 11.]
 [14. 19.]
 [ 9.  8.]
 [10.  7.]
 [ 5.  3.]
 [ 9.  6.]
 [13. 18.]
 [ 8.  7.]
 [ 7.  8.]
 [15.  7.]
 [12. 11.]
 [ 7.  5.]
 [ 7.  6.]
 [11. 11.]
 [10.  6.]]
